openapi: 3.0.3
info:
  title: Music Collection
  version: 0.0.1
servers:
- url: /
paths:
  /info:
    get:
      parameters:
      - explode: true
        in: query
        name: group
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: song
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongDetail'
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /songs:
    get:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetSongsBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Song'
                type: array
          description: List of songs
        "500":
          description: Internal server error
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSongBody'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Song'
          description: Song created
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /songs/{songId}:
    delete:
      parameters:
      - explode: false
        in: path
        name: songId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Song deleted
        "404":
          description: Song not found
        "500":
          description: Internal server error
    patch:
      parameters:
      - explode: false
        in: path
        name: songId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSongBody'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Song'
          description: Song updated
        "404":
          description: Song not found
        "400":
          description: Bad request
        "500":
          description: Internal server error
components:
  schemas:
    SongDetail:
      example:
        releaseDate: 16.07.2006
        link: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        text: "Ooh baby, don't you know I suffer?"
      properties:
        releaseDate:
          example: 16.07.2006
          type: string
        text:
          example: "Ooh baby, don't you know I suffer?"
          type: string
        link:
          example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
          type: string
      required:
      - link
      - releaseDate
      - text
      type: object
    Song:
      example:
        song: Supermassive Black Hole
        releaseDate: 16.07.2006
        link: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        id: 874fdc00-8bb4-4423-894e-01a6a3937883
        text: "Ooh baby, don't you know I suffer?"
        group: Muse
      properties:
        id:
          example: 874fdc00-8bb4-4423-894e-01a6a3937883
          type: string
        group:
          example: Muse
          type: string
        song:
          example: Supermassive Black Hole
          type: string
        releaseDate:
          example: 16.07.2006
          type: string
        text:
          example: "Ooh baby, don't you know I suffer?"
          type: string
        link:
          example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
          type: string
      required:
      - group
      - id
      - link
      - releaseDate
      - song
      - text
      type: object
    GetSongsBody:
      example:
        song: Supermassive Black Hole
        offset: 6
        releaseDate: 16.07.2006
        link: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        limit: 0
        id: 874fdc00-8bb4-4423-894e-01a6a3937883
        text: "Ooh baby, don't you know I suffer?"
        group: Muse
      properties:
        id:
          example: 874fdc00-8bb4-4423-894e-01a6a3937883
          type: string
        group:
          example: Muse
          type: string
        song:
          example: Supermassive Black Hole
          type: string
        releaseDate:
          example: 16.07.2006
          type: string
        text:
          example: "Ooh baby, don't you know I suffer?"
          type: string
        link:
          example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
          type: string
        limit:
          default: 10
          description: Limit the number of songs returned
          type: integer
        offset:
          default: 0
          description: Offset for pagination
          type: integer
      type: object
    CreateSongBody:
      example:
        song: Supermassive Black Hole
        group: Muse
      properties:
        group:
          example: Muse
          type: string
        song:
          example: Supermassive Black Hole
          type: string
      required:
      - group
      - song
      type: object
    UpdateSongBody:
      example:
        song: Supermassive Black Hole
        releaseDate: 16.07.2006
        link: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        text: "Ooh baby, don't you know I suffer?"
        group: Muse
      properties:
        group:
          example: Muse
          type: string
        song:
          example: Supermassive Black Hole
          type: string
        releaseDate:
          example: 16.07.2006
          type: string
        text:
          example: "Ooh baby, don't you know I suffer?"
          type: string
        link:
          example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
          type: string
      type: object
